# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1 


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs: 
  build: 
    docker: 
      - image: circleci/ruby:2.6.3-stretch-node

    working_directory: ~/repo

    steps: 
      - checkout

      - run: 
          name: install dependency
          command: 
            npm install
            gem install percy-cli
      
      # run test!
      - run:
        name: run tests
        command: |
        npm run build
        percy snapshot _site